POST http://localhost:3000/videos
Content-Type: application/json

{
    "title": "Video teste",
    "description": "Este é o primeiro video de Node.js com MySQL",
    "duration": 900
}
###

GET http://localhost:3000/videos
# GET http://localhost:3000/videos

###

PUT http://localhost:3000/videos/b9bfb29f-7981-474c-b989-a293c0c341a5
Content-Type: application/json

{
    "title": "Auterei este video",
    "description": "descrição atualizada",
    "duration": 345
}

###

DELETE  http://localhost:3000/videos/a94d0036-3ab2-4e15-ad00-5d3ff22783c4


